// tests go here; this will not be compiled when this package is used as a library
basic.forever(function () {
    rgbled.SetColor(Color.Red)
    basic.pause(2000)
    rgbled.SetColor(Color.Green)
    basic.pause(2000)
    rgbled.SetColor(Color.Blue)
    basic.pause(2000)
    rgbled.SetColor(Color.Yellow)
    basic.pause(2000)
    rgbled.SetColor(Color.Magenta)
    basic.pause(2000)
    rgbled.SetColor(Color.Cyan)
    basic.pause(2000)
    rgbled.SetColor(Color.White)
    basic.pause(2000)
    rgbled.SetColor(Color.Black)
    basic.pause(4000)
})
